'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UserContext, UserType } from '@/global/userContext';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, setUser] = useState<UserType | null>(null);

  const updateUser = (user: UserType | null) => {
    setUser(user);
  };

  return (
    <html lang="en">
      <UserContext.Provider value={{ user: user, setUser: updateUser }}>
        <body className={inter.className}>{children}</body>
      </UserContext.Provider>
    </html>
  );
}
