export const constants = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

export const NODAL_OFFICER = "NODAL OFFICER";
export const REPORTING_OFFICER = "REPORTING OFFICER";

export const INPROGRESS = "IN-PROGRESS";
export const COMPLETED = "COMPLETED";
export const DELAYED = "DELAYED";
