import LoginForm from "@/components/forms/Login";
import { UserContext } from "@/global/userContext";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Task Management - Login",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="h-[80vh] flex-center">
      <LoginForm />
    </div>
  );
}
